config/routes.rb
Rails.application.routes.draw do
 
  post '/rate' => 'rater#create', :as => 'rate'

  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  mount Ckeditor::Engine => '/ckeditor'
  devise_for :users ,:controllers => {:registrations => "user/registrations", :sessions => "user/sessions"}
  devise_scope :user do
  get "/sign_in" => "home#login"
  get "/sign_up"   => "home#user_signup"
  get "/charity_signup"   => "home#charity_signup"
  get "/account_settings"   => "home#account_settings"
  end

  resources :mysquares
  resources :squares

  
  root 'home#index'
  match '/searching'    => 'home#searching', :via => [:get,:post]
  match '/bets/create' =>'bets#create' , :via =>[:get,:post]
  match '/appeals/create' =>'appeals#create' , :via =>[:get,:post]
  match '/pay' => 'home#pay', :via => [:get,:post]
  get '/search' => 'home#search'
  match '/charity'    => 'charityusersquares#charity', :via => [:get,:post]
  match '/charity/upload'    => 'charity_media#upload', :via => [:get,:post]
  resources :charitychildren

  match '/profile'    => 'home#profile', :via => [:get,:post]
  match '/profile_edit/:id'    => 'home#profile_edit', :via => [:get,:post]
  match '/edit_profile'    => 'home#edit_profile', :via => [:get,:post,:patch]

  get '/charity/remove/:id', to: 'charity_media#remove_picture', as: 'remove_picture'

  match '/charityusersquares/buynow/:id' => 'charityusersquares#buynow' ,as: 'charitybuy_path' ,:via =>[:get,:post]

  resources :charityusersquares
 
  match '/charity_squares'    => 'home#charity_squares', :via => [:get,:post]
  match '/buy_now'    => 'home#buy_now', :via => [:get,:post]
  match '/bets/:id/edit'    => 'bets#edit', :via => [:get,:post]
  match '/bets/:id'    => 'bets#show', as: 'bets_show', :via => [:get,:post]
  match '/update_bet' =>'bets#update' , :via => [:get,:post]
  match '/bets/remove/:id' => 'bets#delete', :via => [:get,:post]
  match '/appeal/:id/edit'    => 'appeals#edit', :via => [:get,:post]
  match '/appeal/:id'    => 'appeals#show', as: 'appeals_show', :via => [:get,:post]
  match '/update_appeal' =>'appeals#update' , :via => [:get,:post]
  match '/auctions'    => 'home#auctions', :via => [:get,:post]
  match '/appeals'    => 'home#appeals', :via => [:get,:post]
  match '/raffle_n_lottery'    => 'home#raffle_n_lottery', :via => [:get,:post]

  match '/view_transaction'    => 'home#view_transaction', :via => [:get,:post]

  
  resources :conversations, only: [:index, :show, :destroy] do
    member do
      post :reply
      post :restore
      delete :empty_trash
      post :mark_as_read
    end
  end

  resources :messages, only: [:new, :create]
  match '/home_page_feed'    => 'home#home_page_feed', :via => [:get,:post]
  match '/search_filter'    => 'home#search_filter', :via => [:get,:post]
  match '/filter'    => 'home#filter', :via => [:get,:post]

  match '/completed_payment_request'    => 'home#completed_payment_request', :via => [:get,:post]
  match '/ipn_notification'    => 'home#ipn_notification', :via => [:get,:post]
  match '/appeal_ipn'  => 'appeals#appeal_ipn', :via => [:get,:post]

  match '/my_square'    => 'home#my_square', :via => [:get,:post]
  
  match '/profile'    => 'home#profile', :via => [:get,:post]
  match '/follow'    => 'charityusersquares#follow', :via => [:get,:post]
  match '/follows'    => 'bets#follows', :via => [:get,:post]
  match '/order_summary'    => 'home#order_summary', :via => [:get,:post]
  match '/bet_response'    => 'bets#bet_response', :via => [:get,:post]
  match '/bet_removepic'    => 'bets#removepic', :via => [:get,:post]
  match '/appeal_donations' => 'appeals#appeal_donations', :via => [:get,:post]
  match '/appeal_removepic'    => 'appeals#removepic', :via => [:get,:post] 
  match '/bet_result/:id'    => 'bets#bet_result', as: 'bet_result', :via => [:get,:post]
  match '/bet_result1/:id'    => 'bets#bet_result1', as: 'bet_result1', :via => [:get,:post]
  match '/view_donations/:id'  => 'appeals#view_donations', as: 'view_donations', :via => [:get,:post]
  match '/purchase/result/:id'    => 'home#purchase_result', as: 'purchase_result', :via => [:get,:post]
  match '/invite'    => 'bets#invite', :via => [:get,:post]

  match '/approve'  => 'bets#approve', :via =>[:get,:post]
  match '/purchase' => 'home#manage_purchase', :via =>[:get,:post]

  match '/checkout'    => 'home#checkout', :via => [:get,:post]
  match '/order_confirmation'    => 'home#order_confirmation', :via => [:get,:post]
  match '/view_transaction'    => 'home#view_transaction', :via => [:get,:post]
  match '/select'    => 'home#select', :via => [:get,:post]
  match '/create_square'    => 'charityusersquares#create_square', :via => [:get,:post]
  match '/bet'    => 'charityusersquares#bet', :via => [:get,:post]
  match '/appeal'  => 'charityusersquares#appeal', :via => [:get,:post]

end

app/models/charityusersquare.rb
class Charityusersquare < ActiveRecord::Base
	belongs_to :user
	has_many :squarebets, :dependent => :destroy
	has_many :squarebids, :dependent => :destroy
	has_many :squarebuynows, :dependent => :destroy
	has_many :squaretickets, :dependent => :destroy
	has_many :charitymedium, :class_name => 'CharityMedia'
    # acts_as_followable
end

app/controllers/charityusersquares_controller.rb
require "instagram"
class CharityusersquaresController < ApplicationController
  before_action :set_charityusersquare, only: [:show, :edit, :update, :destroy]
  respond_to :html, :js
  def index
    @charityusersquares = Charityusersquare.all
    respond_with(@charityusersquares)
  end

  def show
    @follow = Follow.all
    if @follow.empty?
      Charityusersquare.find(params[:id]).update_attributes!(:follow_status => "follow")
      @follow_status = "unfollow"
    end  
    @charitymedia=@charityusersquare.charitymedium
    squareid=@charityusersquare.user_id
    @charity=User.find(squareid)
    @charityname=@charity.charityname
    @charityuser=@charity.firstname
    @charitymission=@charity.mission
    respond_with(@charityusersquare)
  end

  def new
    @bet = Bet.new
    @charityusersquare = Charityusersquare.new
    @charityusersquareid=@charityusersquare.id
    @charitypics=CharityMedia.where(["charity_id = :u", { u: @charityusersquareid }])
       @charity=User.where("role = ?", 'charity')
    @list=[]
    @charity.each do |i|
      @list << [i.charityname,i.id]
    end
    respond_with(@charityusersquare)
  end

  def remove_picture
  render :plain =>" tst"
  end

  def edit
    @charityusersquareid=@charityusersquare.id
    @charitypics=CharityMedia.where(["charityusersquare_id = :u", { u: @charityusersquareid }])
 
  end
  
  def getpics
  @charitypics=CharityMedia.where(["charityusersquare_id = :u", { u: @charityusersquareid }])
  # render :plain => @charitypics.inspect
  
  end

  def create

    @charityusersquare = Charityusersquare.new(charityusersquare_params)
    @charityusersquare.user_id=current_user.id
    @charityusersquare.save
    respond_with(@charityusersquare)
  end

  def update
    @charityusersquare.update(charityusersquare_params)
    respond_with(@charityusersquare)
  end

  def destroy
    @charityusersquare.destroy
    respond_with(@charityusersquare)
  end

  def charity
    if current_user == nil
      new_user_session_path
    else
      @charity = current_user.charityusersquares
    end  
      charity_path
  end  

  def buynow
   render :plain =>params.inspect  
  end

  def follow
    # @follow = Follow.all
    #   if current_user.follows?(Charityusersquare.find(params[:id]))
    #     @follow_status = "unfollow"
    #     Charityusersquare.find(params[:id]).update_attributes!(:follow_status => "follow")
    #     current_user.unfollow!(Charityusersquare.find(params[:id]))
    #   else  
    #     @follow_status = "follow"
    #     Charityusersquare.find(params[:id]).update_attributes!(:follow_status => "unfollow")
    #     current_user.follow!(Charityusersquare.find(params[:id])) 
    #   end  
    # respond_to do |format|
    #   format.js 
    # end

  end 

  # def connect
  #   redirect_to Instagram.authorize_url(:redirect_uri => CALLBACK_URL)
  # end

  # def callback
  #   binding.pry
  #   response = response = Instagram.get_access_token(params[:code], :redirect_uri => CALLBACK_URL, :client_secret => "160a455eee9d4133b0ccf8a1c492b2d0")
  #   session[:access_token] = response.access_token
  #   redirect_to :controller => 'Charityusersquares', :action => 'index'
  # end 

  def create_square

  end

  def bet
    @bet = Bet.new
    @charityusersquare = Charityusersquare.new
    @charityusersquareid=@charityusersquare.id
    @charitypics=CharityMedia.where(["charity_id = :u", { u: @charityusersquareid }])
       @charity=User.where("role = ?", 'charity')
    @list=[]
    @charity.each do |i|
      @list << [i.charityname,i.id]
    end
    respond_with(@charityusersquare)
  end
  
  def appeal
    @appeal= Appeal.new
    @charityusersquare = Charityusersquare.new
    @charityusersquareid=@charityusersquare.id
    @charitypics=CharityMedia.where(["charity_id = :u", { u: @charityusersquareid }])
       @charity=User.where("role = ?", 'charity')
    @list=[]
    @charity.each do |i|
      @list << [i.charityname,i.id]
    end
    respond_with(@charityusersquare)
  end  
  
  private
    def set_charityusersquare
      @charityusersquare = Charityusersquare.find(params[:id])
    end

    def charityusersquare_params
      params.require(:charityusersquare).permit(:user_id, :brand, :condition, :types, :color, :charitytype ,:sizeinfo ,:name ,:material,:description, :daysleft, :price)
    end
end

app/helpers/charityusersquares_helper.rb
module CharityusersquaresHelper
end

app/views/charityusersquares/_form.html.erb
<%= form_for(@charityusersquare) do |f| %>
  <% if @charityusersquare.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@charityusersquare.errors.count, "error") %> prohibited this charityusersquare from being saved:</h2>
      <ul>
      <% @charityusersquare.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

   <div class="field">

    <%= f.label :charitytype %><br>
    <%= f.select :charitytype, ["Lottery","Raffles","Bets","Appeals","Auctions", "Bid"] %>
  
  </div>

  <div class="field " >
  <%= f.label "Days Left" %><br>
  <%= f.text_field :daysleft %>
  </div>

  <div class="field charityusersquare_price" style="display:none">
  <%= f.label "amount" %><br>
  <%= f.text_field :price %>
  </div>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>

  <div class="field">
    <%= f.label :material %><br>
    <%= f.text_field :material %>
  </div>
  
    <div class="field">
    <%= f.label :Description %><br>
    <%= f.text_field :description %>
  </div -->

   <div class="field"> 
    <%= f.label :Condition %><br>
    <%= f.select :condition, ["New","Used","Not specified"] %>
 
 </div> 
 
  <div class="field">
    <%= f.label :Types %><br>
    <%= f.text_field :types %>
  </div>
   <div class="field"> 
    <%= f.label :Color %>
    <%= f.text_field :color %>
   </div> 

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>


<script>
// $( '#charity_media' )
//   .submit( function( e ) {
//     $.ajax( {
//       url: $(this).attr('action'),
//       type: 'POST',
//       data: new FormData( this ),
//       processData: false,
//       contentType: false
//     } );
//     e.preventDefault();
//   } );

$(document).ready(function(){

$('#charityusersquare_charitytype').on('change', function() {
 var value=  this.value
 console.log(value)
 if(value == "Appeals" || value== "Auctions" || value == "Raffles")
  { 
    $(".charityusersquare_price").fadeIn("slow");
}else{
    $(".charityusersquare_price").fadeOut("slow");
}

 
})
});
</script>

app/views/charityusersquares/appeal.html.erb
<div class="off-canvas-wrap docs-wrap" data-offcanvas="">
  <div class="inner-wrap">
    <%= render 'layouts/header' %>
      <div class="inner_grey_bg">
        <div class='row'>
          <div class="create_squar_bet  create_squar left">
            <% if notice %>
              <p class="alert alert-success"><%= notice %></p>
            <% end %>
            <% if alert %>
              <div data-alert class="alert-box success radius">
                <%= alert %>
                <a href="#" class="close">&times;</a>
              </div>
            <% end %>

            <div class="select_type">
              <div class="small-12 columns">
                <h1>Enter Details for your Appeal</h1>
              </div>
              <div class='field large-6 columns select_square'>
                <!-- <label>Select Square type</label>
                <select name="mydropdown">
                  <option value="lottery">Lottery</option>
                  <option value="bet">Bet</option>
                  <option value="appeal">Appeal</option>
                  <option value="auction">Auction</option>
                  <option value="bid">Bid</option>
                  <option value="raffles">Raffles</option>
                </select> -->
              </div>
            </div>

            <div class='appeal'>
              <%= form_for(@appeal, :url =>  appeals_create_path, :html => { :multipart => true ,:novalidate=>"novalidate"} )  do |f| %>
                <div class="images_url row">
                </div> 

                <div id="errorExplanation">
                  <%= flash["error"] %>
                </div>

                <!-- <div class='field large-6 columns'> -->
                <!-- <label>Select Square type</label> -->
                 <%#= f.select :charitytype, ["Lottery","Raffles","Bets","Appeals","Auctions", "Bid"] %>
                <!-- </div> -->

                <div class="hide">
                  <%=f.number_field :user_id , :value=>current_user.id %>
                </div>

                <% if !@list.nil? %>
                  <div class='field large-6 columns'>
                    <%= f.label "Select a charity" %>
                    <%= f.select :charityusersquare_id , @list %>
                  </div>
                <% end %>  

                <!--<div class="field large-6 columns">
                  <%#= f.label "Name" %>
                  <%#= f.text_field :name %>
                </div> -->
                <%= f.hidden_field :charitytype, :value => params[:charitytype]%>

                <div class="field large-12 columns form-group"> 
                  <%= f.label "Description" %>
                  <%= f.text_area :description,:placeholder => "Enter description" %>
                </div>

                <div class='field large-6 columns'>
                  <%= f.label "Type" %> 
                  <%#binding.pry%>
                  <%= f.select :appeal_type, options_for_select(["Select Square", "General", "Specific"], :selected => params[:appeal_type]) %>
                  <%#= f.select(:appeal_type, ["General", "Specific"], {:prompt => "appeal_type"}, :onchange => "location.href = '#{request.url}'")%>
                </div>

                <div class="field large-6 columns">
                  <%= f.label "Ending date" %>
                  <%= f.text_field :enddate ,{:class => 'datetimepicker', :placeholder => 'Appeal end date ',:required => true            } %>
                </div>

                <div class='field large-6 columns specific'>
                  <%= f.label :specific_appeal_description, "Appeal Description" %>
                  <%= f.text_field :specific_appeal_description %>
                </div>

                <div class="create_squar_upload_image left">
                  <div class="large-3 medium-4 small-12 columns">
                     <div id="holder"></div> 
                     <label> Add Photos </label>
                      <div class="upload_image_squar text-center">
                        <p>Click here or <br> drag &amp; drop</p>
                        <input id="file" name="appeal[logo]" type="file" required>
                      </div>
                  </div>
                  <div class="large-9 medium-8 small-12 columns">
                    <label>Delete or rearrange your images</label>
                    <div class="upload-preview"></div>
                  </div>    
                </div>   

                <div class="field bottom_ceate_bet_btn large-12 columns">
                  <%= f.submit "Create Appeal " , :class=>'button success left' %>
                </div>

              <% end %>
            </div>

        </div>
      </div>
  </div>
</div>
<%= render 'layouts/footer' %>    


<script>
$(document).ready(function(){
  // alert("on load");
  
$(".upload-preview").sortable({
    placeholder: "ui-state-highlight",
    helper: 'clone',
    sort: function(e, ui) {
        //$(ui.placeholder).html(Number($("#sortable_nav > li:visible").index(ui.placeholder)) + 1);
    },
    update: function(event, ui) {
        var $lis = $(this).children('div');
        $lis.each(function() {
            var $li = $(this);
            var newVal = $(this).index() + 1;
            $(this).attr("val",newVal);
            $(this).children('#item_display_order').val(newVal);
        });
    }
});
$(".upload-preview").disableSelection();
$('.th').click(function(){
 var id= $(this).attr('id');
 $('.'+id).fadeIn(); 
})

$('.datetimepicker').datetimepicker();


/* validations for the form  */
$('.button.success').click(function(e){
  
   
        //e.preventDefault();

            //form validation rules
            $("#new_appeal").validate({
                rules: {
                    'appeal[description]': "required"
                },
                messages: {
                    'appeal[description]': "Please enter description *"
                },
                submitHandler: function(form) {
                    console.log('submit');
                    form.submit();
                }
            });


})

  $('#appeal_appeal_type').change(function() {
      location.reload();
  });  
  if ($("#appeal_appeal_type :selected").text() == "Specific")
  {
    $(".specific").show();

  }
  else {
    $(".specific").hide();
  }
 
  });
/* end */

</script>

<script src="http://ajax.aspnetcdn.com/ajax/jquery.validate/1.9/jquery.validate.min.js"></script>

<script src="https://code.jquery.com/ui/1.11.3/jquery-ui.js"></script>
<style>
  button.success, .button.success {
    background-color: #43ac6a;
    border-color: #368a55;
    color: #ffffff;
    margin: 19px 19px 19px 0;
  }
  /* Error container for form C */

        #error-container div {
            color: red;
            line-height: 140%;
        }

        #error-container div:last-child {
            padding-bottom: 10px;
        }
        h1{
          font-family: "dinmedium";
        }
</style>

app/views/charityusersquares/bet.html.erb
<div class="off-canvas-wrap docs-wrap" data-offcanvas="">
  <div class="inner-wrap">
    <%= render 'layouts/header' %>
      <div class="inner_grey_bg">
        <div class='row'>
          <div class="create_squar_bet  create_squar left">
            <% if notice %>
              <p class="alert alert-success"><%= notice %></p>
            <% end %>
            <% if alert %>
              <div data-alert class="alert-box success radius">
                <%= alert %>
                <a href="#" class="close">&times;</a>
              </div>
            <% end %>

            <div class="select_type">
              <div class="small-12 columns">
                <h1>Enter Details for your Bet</h1>
              </div>
              <div class='field large-6 columns select_square'>
                <!-- <label>Select Square type</label>
                <select name="mydropdown">
                  <option value="lottery">Lottery</option>
                  <option value="bet">Bet</option>
                  <option value="appeal">Appeal</option>
                  <option value="auction">Auction</option>
                  <option value="bid">Bid</option>
                  <option value="raffles">Raffles</option>
                </select> -->
              </div>
            </div>

            <div class='bet'>
              <%= form_for(@bet, :url =>  bets_create_path, :html => { :multipart => true ,:novalidate=>"novalidate"} )  do |f| %>
                <div class="images_url row">
                </div> 

                <div id="errorExplanation">
                  <%= flash["error"] %>
                </div>

                <!-- <div class='field large-6 columns'> -->
                <!-- <label>Select Square type</label> -->
                 <%#= f.select :charitytype, ["Lottery","Raffles","Bets","Appeals","Auctions", "Bid"] %>
                <!-- </div> -->

                <div class="hide">
                  <%=f.number_field :user_id , :value=>current_user.id %>
                </div>

                <% if !@list.nil? %>
                  <div class='field large-6 columns'>
                    <%= f.label "Select a charity" %>
                    <%= f.select :charityusersquare_id , @list %>
                  </div>
                <% end %>  

                <!--<div class="field large-6 columns">
                  <%#= f.label "Name" %>
                  <%#= f.text_field :name %>
                </div> -->

                <div class="field large-12 columns form-group"> 
                  <%= f.label "Description" %>
                  <%= f.text_area :description,:placeholder => "Enter bet description" %>
                </div>

                <div class="field large-6 columns">
                  <%= f.label "Ending date" %>
                  <%= f.text_field :enddate ,{:class => 'datetimepicker', :placeholder => 'Bet end date ',:required => true            } %>
                </div>
                
                <%= f.hidden_field :charitytype, :value => params[:charitytype]%>

                <div class='field large-6 columns'>
                  <%= f.label "I bet" %> 
                  <%= f.number_field :amount ,:placeholder=>'Enter amount in $', :min=> 1  %>
                </div>

                <div class='field large-6 columns'>
                  <label>that</label> 
                  <%= f.text_field :subject, :placeholder =>'Please enter the bet subject' ,:required => true %>
                </div>

                <div class='field large-6 columns'>
                  <label>will</label>  
                  <%= f.text_field :objective, :placeholder =>'Please enter the bet objective', :required => true %>
                </div>

	              <div class="create_squar_upload_image left">
	              	<div class="large-3 medium-4 small-12 columns">
	              	   <div id="holder"></div> 
	              	   <label> Add Photos </label>
	              	   	<div class="upload_image_squar text-center">
	              	   		<p>Click here or <br> drag &amp; drop</p>
	              	   		<input id="file" name="bet[logo]" type="file" required>
	              	   	</div>
	              	</div>
	              	<div class="large-9 medium-8 small-12 columns">
	              		<label>Delete or rearrange your images</label>
	              		<div class="upload-preview"></div>
	              	</div>    
	              </div>   

                <div class="invite large-12 left">         
                  <%#= form_tag invite_path, method: :post do %>
                  	<div class="small-12 columns">
                    		<%= label_tag 'recipients', 'Invite users to bet' %>
                    	</div> 
                    	<div class="large-6 medium-6 small-12 columns"> 
	                    <p><%= select_tag 'recipients', recipients_options, multiple: true, :required => true, class: 'form-control chosen-it', data: { placeholder: "Select Registered Users" } %></p>
	                    <div class='invite_btn left' >Invite more users</div>
	                </div> 
	                  <div class="large-6 medium-6 small-12 columns"> 
	                    <div class='invite_sub' style='display:none'>
	                      <p><%= text_field_tag 'custom_recipients', nil, :placeholder => 'Add email and press enter', :class => "tm-input"  %></p>
	                      <p><%= hidden_field_tag 'url', request.original_url %></p>
	                      <p><%= hidden_field_tag 'bet_id', params[:id].to_i %></p>
	                    </div>
	                  </div> 
                    <p><%#= submit_tag 'Send', class: 'tiny button' %></p>
                  <%# end %> 
                  <div class="msg large-12 columns">
                  </div>                
                </div> 

                <div class="field bottom_ceate_bet_btn large-12 columns">
                  <%= f.submit "Create Bet " , :class=>'button success' %>
                </div>

              <% end %>
            </div>

          </div>
      </div>
  </div>
</div>
<%= render 'layouts/footer' %> 

<script>
$(document).ready(function(){
  // alert("on load");

$(".upload-preview").sortable({
    placeholder: "ui-state-highlight",
    helper: 'clone',
    sort: function(e, ui) {
        //$(ui.placeholder).html(Number($("#sortable_nav > li:visible").index(ui.placeholder)) + 1);
    },
    update: function(event, ui) {
        var $lis = $(this).children('div');
        $lis.each(function() {
            var $li = $(this);
            var newVal = $(this).index() + 1;
            $(this).attr("val",newVal);
            $(this).children('#item_display_order').val(newVal);
        });
    }
});
$(".upload-preview").disableSelection();

$('.th').click(function(){
 var id= $(this).attr('id');
 $('.'+id).fadeIn(); 
})

$('.datetimepicker').datetimepicker();


jQuery(".tm-input").tagsManager();
$('.chosen-it').chosen();



  $('.invite_btn').click(function(e){
    e.preventDefault();
    $('.invite_sub').toggle();

  });


/* validations for the form  */
$('.button.success').click(function(e){
  
   
        //e.preventDefault();

            //form validation rules
            $("#new_bet").validate({
                rules: {
                    'bet[description]': "required",
                    'bet[amount]': "required",
                    'bet[subject]': "required",
                    'bet[objective]':"required"

                   
                },
                messages: {
                    'bet[description]': "Please enter bet description *",
                    'bet[amount]': "Please enter bet amount ",
                    'bet[subject]': "Please enter bet subject ",
                    'bet[objective]':"Please enter bet objective"
                    
                },
                submitHandler: function(form) {
                    console.log('submit');
                    form.submit();
                }
            });


})

  });
/* end */

</script>

<script src="http://ajax.aspnetcdn.com/ajax/jquery.validate/1.9/jquery.validate.min.js"></script>

<script src="https://code.jquery.com/ui/1.11.3/jquery-ui.js"></script>


<style>
  button.success, .button.success {
    background-color: #43ac6a;
    border-color: #368a55;
    color: #ffffff;
    margin: 19px 19px 19px 0;
  }
  /* Error container for form C */

        #error-container div {
            color: red;
            line-height: 140%;
        }

        #error-container div:last-child {
            padding-bottom: 10px;
        }
        h1{
          font-family: "dinmedium";
        }
</style>


            

app/views/charityusersquares/charity.html.erb
<%= render 'layouts/navigation' %>
<br/>
<%= link_to "Create Square", new_charityusersquare_path, :class => "button tiny radius", :style => "float:right;" %>
<%= link_to "Create Child", new_charitychild_path, :class => "button tiny radius", :style => "margin-left:750px;width:110px;" %>
<h3>My Squares</h3>
<% unless @charity.nil? %>
  <% @charity.each do |c| %>
    <a href=<%="/charityusersquares/#{c.id}"%>>
      <div class="pricing-table medium-4 columns">
        <div class="panel callout radius">
          <li>Types: <%= c.name %></li>
          <li>Brand: <%= c.types %></li>
          <li>Condition: <%= c.material %></li>
        </div> 
        <li class="title"><%= c.charitytype %></li>
      </div>
    </a> 
  <% end %>  
<% end %>




<%= render 'layouts/footer' %>

<style>
	.pricing-table {
	    text-align : center;
	    margin-top: 40px;
	    margin-right:15px;
	    width: 28%;
	} 
</style>

app/views/charityusersquares/edit.html.erb
<%= render 'layouts/navigation' %>
<h1>Editing charityusersquare</h1>

<div class='media'>
   Your Photos

  <% @charitypics.each do |pics|%>
  <img height='100px' width='100px' src=<%=pics.picture%>>
  <%= link_to 'remove',  remove_picture_path(pics.id), :confirm => "Are you sure?",:method => "GET"%>
  
  <%end%>

   <%= form_for(:charity_media ,url: charity_upload_path ,:html => {:id=>"charity_media"}) do |f| %>
   <%= f.file_field :picture, autocomplete: "off" ,placeholder:"Picture" %>
   <%= f.hidden_field :squareid, autocomplete: "off",:value =>@charityusersquareid %>
  
    <button class='mform'>Upload</button> 
   <%end%>
 </div> 
<%= render 'form' %>

<%= link_to 'Show', @charityusersquare %> |
<%= link_to 'Back', charity_path %>
<%= render 'layouts/footer' %>

app/views/charityusersquares/follow.js.erb
<% if @follow_status == "follow"%>
    $('#follow').html('unfollow')
<%else%>
    $('#follow').html('follow')
<%end%>

app/views/charityusersquares/index.html.erb
  <%= render 'layouts/navigation' %>
<h1>Listing charityusersquares</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @charityusersquares.each do |charityusersquare| %>
      <tr>
        <td><%= link_to 'Show', charityusersquare %></td>
        <td><%= link_to 'Edit', edit_charityusersquare_path(charityusersquare) %></td>
        <td><%= link_to 'Destroy', charityusersquare, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Charityusersquare', new_charityusersquare_path %>