config/routes.rb
Rails.application.routes.draw do
 
  post '/rate' => 'rater#create', :as => 'rate'

  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  mount Ckeditor::Engine => '/ckeditor'
  devise_for :users ,:controllers => {:registrations => "user/registrations", :sessions => "user/sessions"}
  devise_scope :user do
  get "/sign_in" => "home#login"
  get "/sign_up"   => "home#user_signup"
  get "/charity_signup"   => "home#charity_signup"
  get "/account_settings"   => "home#account_settings"
  end

  resources :mysquares
  resources :squares

  
  root 'home#index'
  match '/searching'    => 'home#searching', :via => [:get,:post]
  match '/bets/create' =>'bets#create' , :via =>[:get,:post]
  match '/appeals/create' =>'appeals#create' , :via =>[:get,:post]
  match '/pay' => 'home#pay', :via => [:get,:post]
  get '/search' => 'home#search'
  match '/charity'    => 'charityusersquares#charity', :via => [:get,:post]
  match '/charity/upload'    => 'charity_media#upload', :via => [:get,:post]
  resources :charitychildren

  match '/profile'    => 'home#profile', :via => [:get,:post]
  match '/profile_edit/:id'    => 'home#profile_edit', :via => [:get,:post]
  match '/edit_profile'    => 'home#edit_profile', :via => [:get,:post,:patch]

  get '/charity/remove/:id', to: 'charity_media#remove_picture', as: 'remove_picture'

  match '/charityusersquares/buynow/:id' => 'charityusersquares#buynow' ,as: 'charitybuy_path' ,:via =>[:get,:post]

  resources :charityusersquares
 
  match '/charity_squares'    => 'home#charity_squares', :via => [:get,:post]
  match '/buy_now'    => 'home#buy_now', :via => [:get,:post]
  match '/bets/:id/edit'    => 'bets#edit', :via => [:get,:post]
  match '/bets/:id'    => 'bets#show', as: 'bets_show', :via => [:get,:post]
  match '/update_bet' =>'bets#update' , :via => [:get,:post]
  match '/bets/remove/:id' => 'bets#delete', :via => [:get,:post]
  match '/appeal/:id/edit'    => 'appeals#edit', :via => [:get,:post]
  match '/appeal/:id'    => 'appeals#show', as: 'appeals_show', :via => [:get,:post]
  match '/update_appeal' =>'appeals#update' , :via => [:get,:post]
  match '/auctions'    => 'home#auctions', :via => [:get,:post]
  match '/appeals'    => 'home#appeals', :via => [:get,:post]
  match '/raffle_n_lottery'    => 'home#raffle_n_lottery', :via => [:get,:post]

  match '/view_transaction'    => 'home#view_transaction', :via => [:get,:post]

  
  resources :conversations, only: [:index, :show, :destroy] do
    member do
      post :reply
      post :restore
      delete :empty_trash
      post :mark_as_read
    end
  end

  resources :messages, only: [:new, :create]
  match '/home_page_feed'    => 'home#home_page_feed', :via => [:get,:post]
  match '/search_filter'    => 'home#search_filter', :via => [:get,:post]
  match '/filter'    => 'home#filter', :via => [:get,:post]

  match '/completed_payment_request'    => 'home#completed_payment_request', :via => [:get,:post]
  match '/ipn_notification'    => 'home#ipn_notification', :via => [:get,:post]
  match '/appeal_ipn'  => 'appeals#appeal_ipn', :via => [:get,:post]

  match '/my_square'    => 'home#my_square', :via => [:get,:post]
  
  match '/profile'    => 'home#profile', :via => [:get,:post]
  match '/follow'    => 'charityusersquares#follow', :via => [:get,:post]
  match '/follows'    => 'bets#follows', :via => [:get,:post]
  match '/order_summary'    => 'home#order_summary', :via => [:get,:post]
  match '/bet_response'    => 'bets#bet_response', :via => [:get,:post]
  match '/bet_removepic'    => 'bets#removepic', :via => [:get,:post]
  match '/appeal_donations' => 'appeals#appeal_donations', :via => [:get,:post]
  match '/appeal_removepic'    => 'appeals#removepic', :via => [:get,:post] 
  match '/bet_result/:id'    => 'bets#bet_result', as: 'bet_result', :via => [:get,:post]
  match '/bet_result1/:id'    => 'bets#bet_result1', as: 'bet_result1', :via => [:get,:post]
  match '/view_donations/:id'  => 'appeals#view_donations', as: 'view_donations', :via => [:get,:post]
  match '/purchase/result/:id'    => 'home#purchase_result', as: 'purchase_result', :via => [:get,:post]
  match '/invite'    => 'bets#invite', :via => [:get,:post]

  match '/approve'  => 'bets#approve', :via =>[:get,:post]
  match '/purchase' => 'home#manage_purchase', :via =>[:get,:post]

  match '/checkout'    => 'home#checkout', :via => [:get,:post]
  match '/order_confirmation'    => 'home#order_confirmation', :via => [:get,:post]
  match '/view_transaction'    => 'home#view_transaction', :via => [:get,:post]
  match '/select'    => 'home#select', :via => [:get,:post]
  match '/create_square'    => 'charityusersquares#create_square', :via => [:get,:post]
  match '/bet'    => 'charityusersquares#bet', :via => [:get,:post]
  match '/appeal'  => 'charityusersquares#appeal', :via => [:get,:post]

end

app/models/bet.rb
class Bet < ActiveRecord::Base

  validates_presence_of :charityusersquare_id, :amount, :description, :enddate

  # acts_as_followable
  has_many :bet_results, dependent: :destroy
  has_many :bet_responses, dependent: :destroy
  has_many :payment_details, dependent: :destroy
  has_many :charitymedium, :class_name => 'CharityMedia', dependent: :destroy
end

app/controllers/bets_controller.rb
class BetsController < ApplicationController
  include ActionView::Helpers::DateHelper
  before_action :set_bet, only: [:show, :edit,  :destroy]
  before_action :create, only: [:create]

  respond_to :html,:js

  def index
    @bets = Bet.all
    respond_with(@bets)
  end
   
  def show
    if !current_user.nil?
      sign_out current_user
    end
    sign_in User.find(params[:user_id].to_i)
    @tz = Geocoder.search(current_user.current_sign_in_ip)[0].data["timezone"]
    
    # @tz = TimeZone::Local.get()

    #@time_left = distance_of_time_in_words(Bet.find(params[:id]).enddate, Bet.find(params[:id]).startdate)
    # @time_left=2
    # @inv_users = InvitedUser.all

    # if @time_left == "less than a minute"
    #   if @inv_users.count == 1                                           
    #     if BetResult.find_by_bet_id(params[:id]).answer == BetResponse.find_by_user_id(@inv_users.first.user_id).response
    #       UserMailer.bet_result(User.find(@inv_users.first.user_id).email, "win").deliver
    #     else  
    #       UserMailer.bet_result(User.find(@inv_users.first.user_id).email, "lose").deliver
    #     end
    #   else
    #    @inv_users.each do |i|
    #     if BetResult.find_by_bet_id(params[:id]).answer == BetResponse.find_by_user_id(i.user_id).response
    #       UserMailer.bet_result(User.find_by_id(i.user_id).email, "win").deliver
    #     else 
    #       UserMailer.bet_result(User.find_by_id(i.user_id).email, "lose").deliver
    #     end
    #    end 
    #   end     
    # end  
     
    respond_with(@bet)
  end

  def new
    @bet = Bet.new
  end

  def edit

    @crtrlr = params[:controller]
    @charityusersquare = Charityusersquare.new
    @charityusersquareid=@charityusersquare.id
    @charitypics=CharityMedia.where(["charityusersquare_id = :u", { u: @bet.id }])
    @charity=User.where("role = ?", 'charity')
    @list=[]
    @charity.each do |i|
    @list << [i.charityname,i.id]
   
    end
  end

  def create
    @bet = Bet.new(bet_params)
    @bet.user_id=params[:bet][:user_id]
    @tz = Geocoder.search(current_user.current_sign_in_ip)[0].data["timezone"]
    @bet.startdate = Time.now.in_time_zone(@tz).to_s
    if params[:bet][:enddate].present?
      @bet.enddate = params[:bet][:enddate].in_time_zone(@tz).to_s
    end
    # UserMailer.bet_result1(@bet.startdate, @bet.enddate).deliver   
    @bet.charitytype=@bet.charitytype.downcase
    @bet.active = true
     if @bet.save
      # entry in bet response #
      @br=BetResponse.new
      @br.bet_id=@bet.id
      @br.user_id=@bet.user_id
      @br.response= 1
      @br.save
      #end#
      
      bet_id=@bet.id
      @params = params
      unless @params[:recipients].nil?
      @params[:recipients].each do |f|
        @invite = InvitedUser.new
        @invite.user_id = f.to_i
        @invite.user_email = User.find(f.to_i).email
        @invite.bet_id = @bet.id
        @invite.save
        UserMailer.invite(@params, User.find_by_id(f.to_i), @bet.id).deliver
      end 
     end 

     unless @params["hidden-custom_recipients"].split(',').nil?
      @params["hidden-custom_recipients"].split(',').each do |p|
        @invite = InvitedUser.new
        @invite.bet_id = @bet.id
        @invite.user_email = p
        @invite.save
        UserMailer.invite1(@params, p, @bet.id).deliver
      end 
     end 
      
     if params[:image_array]
     temp=[]
     params[:image_array].each do |encoded_img|
      

     bet_media= CharityMedia.new(:charityusersquare_id=>bet_id)
     bet_media.save
     created_bet_id=bet_media.id
     path="#{Rails.root}/public/images/#{created_bet_id}.jpg"
     temp.push path
         File.open("#{path}","wb") do |file|
         file.write(Base64.decode64(encoded_img.split(/,/)[1]))
         end
        
     @update=CharityMedia.find(created_bet_id)
     @update.picture=@update.id
     @update.save()
      # image = MiniMagick::Image.open("#{path}")
      # image.resize("192x140!")
      # image.format("png", 1)
      # image.write("#{path}")
      end
      end

      @bet.startdate=@bet.startdate.to_time.in_time_zone(@tz)
      @bet.enddate=@bet.enddate.to_time.in_time_zone(@tz)
      @time_left = distance_of_time_in_words(@bet.enddate, @bet.startdate)
      # @time_in_minutes=(params[:bet][:enddate].to_time - @bet.startdate.to_time)/60
      @time_in_minutes=(@bet.enddate.to_time - @bet.startdate.to_time)/60
      
      @time_enque=@time_in_minutes.floor
  
      Delayed::Job.enqueue(MailingJob.new(@bet.user_id, @bet.id, params[:bet][:amount].to_i), -3, @time_enque.minutes.from_now.in_time_zone(@tz))
      flash[:notice]= "Bet Created" 
      redirect_to my_square_path
      else
         
       flash[:alert] = @bet.errors.full_messages.to_sentence
      
       
        # flash[:notice] = @abc.to_a[0] + @abc.to_a[1] + @abc.to_a[2]
        # render 'charityusersquare/new'
      redirect_to(new_charityusersquare_path) 
      # render 'charityusersquares/new'
     end
  end

  def update
    # binding.pry
     @tz = Geocoder.search(current_user.current_sign_in_ip)[0].data["timezone"]

     @betid=params[:bet][:id]

     @bet=Bet.find(@betid)
     @startdate = Time.now.in_time_zone(@tz).to_s
    if params[:bet][:enddate].present?
      @enddate = params[:bet][:enddate].in_time_zone(@tz).to_s
    end

    # UserMailer.bet_result1(@bet.startdate, @bet.enddate).deliver   
    @bet.update_attributes!(:user_id => params[:bet][:user_id] , :charityusersquare_id =>params[:bet][:charityusersquare_id], :description => params[:bet][:description], :amount => params[:bet][:amount] , :subject =>params[:bet][:subject], :objective =>params[:bet][:objective], :enddate =>@enddate, :charitytype=>params[:bet][:charitytype].downcase)
   
      bet_id=@betid
      @params = params
          #mail #
                #binding.pry
                unless @params[:recipients].nil?
                @params[:recipients].each do |f|
                  @invite = InvitedUser.new
                  @invite.user_id = f.to_i
                  @invite.user_email = User.find(f.to_i).email
                  @invite.bet_id = @bet.id
                  @invite.save
                  UserMailer.invite(@params, User.find_by_id(f.to_i), @bet.id).deliver
                end 
                end 
          if params[:image_array]
           temp=[]
           params[:image_array].each do |encoded_img|
            

           bet_media= CharityMedia.new(:charityusersquare_id=>bet_id)
           bet_media.save
           created_bet_id=bet_media.id
           path="#{Rails.root}/public/images/#{created_bet_id}.jpg"
           temp.push path
               File.open("#{path}","wb") do |file|
               file.write(Base64.decode64(encoded_img.split(/,/)[1]))
               end
              
           @update=CharityMedia.find(created_bet_id)
           @update.picture=@update.id
           @update.save()
            # image = MiniMagick::Image.open("#{path}")
            # image.resize("192x140!")
            # image.format("png", 1)
            # image.write("#{path}")
            end
            end

      @startdate=@startdate.to_time.in_time_zone(@tz)
      @enddate=@enddate.to_time.in_time_zone(@tz)
      @time_left = distance_of_time_in_words(@enddate, @startdate)
      # @time_in_minutes=(params[:bet][:enddate].to_time - @bet.startdate.to_time)/60
      @time_in_minutes=(@enddate.to_time - @startdate.to_time)/60
      
      @time_enque=@time_in_minutes.floor
  
      Delayed::Job.enqueue(MailingJob.new(@bet.user_id, @bet.id, params[:bet][:amount].to_i), -3, @time_enque.minutes.from_now.in_time_zone(@tz))
      flash[:notice]= "Bet Updated" 
      redirect_to my_square_path
    


   
   
  end

  def destroy
    @bet.destroy
    respond_with(@bet)
  end

  def delete 
    @delbet=params[:id]
    Bet.find(@delbet).delete
        BetResponse.where(:bet_id => @delbet).each do |bet|
          bet.delete
        end
        BetResult.where(:bet_id => @delbet).each do |bet|
          bet.delete
        end
        CharityMedia.where(:charityusersquare_id => @delbet).each do |media|
          media.delete
          File.delete(Rails.root + "public/images/#{media.picture.to_s}.jpg")
        end  
  end


  def follows
    @follow = Follow.all
      if current_user.follows?(User.find(params[:id]))
        @follow_status = "unfollow"
        User.find(params[:id]).update_attributes!(:follow_status => "follow")
        current_user.unfollow!(User.find(params[:id]))
      else  
        @follow_status = "follow"
        User.find(params[:id]).update_attributes!(:follow_status => "unfollow")
        current_user.follow!(User.find(params[:id])) 
      end  
    respond_to do |format|
      format.js 
    end
  end 

  def bet_response
    @bet = BetResponse.new
    if params[:response] == "yes"
      @bet.response = true
    else 
      @bet.response = false
    end  
      @bet.user_id = current_user.id
      @bet.bet_id = params[:id]
      if BetResponse.where('user_id=? and bet_id=?', current_user.id, params[:id]).present? 
        flash[:alert] = "You have already Placed this Bet!!!"
      else 
        @bet.save
        flash[:notice] = "Your Bet has been Placed!!!" 
      end 
      redirect_to :back
  end


  def bet_result
    @betres = BetResult.new
    if params[:response] == "yes"
      @betres.answer = true
    else 
      @betres.answer = false
    end  
    @betres.bet_id = params[:bet_id]
    @betres.save
    Bet.find(@betres.bet_id).update_attributes!(:active => false)

    flash[:notice] = "Your have set the bet result!!!" 
    @response = BetResponse.where("bet_id=?", params[:id])
    @response.each do |resp|
      UserMailer.bet_result(resp, @betres.answer).deliver
    end
    # respond_to do |format|
     #  format.js 
    # end
     redirect_to :back
  end

  def bet_result1
    @bet_response = BetResponse.where("bet_id=?", params[:id])
  end  

  def removepic

   @mediaid=params[:pic]
   CharityMedia.find(@mediaid).destroy

app/helpers/bet_helper.rb
module BetHelper
end

app/helpers/bets_helper.rb
module BetsHelper
end

app/views/bets/_apply_result.html.erb
<div class="betresult_link pending_squre">
    <span class="text_white left">Completed</span>
    <%= link_to "View Results", bet_result1_path(:id=>@betres.bet_id) , :class => "review right", :style=>"width:121px;" %>
</div>

app/views/bets/_form.html.erb
  <%= render 'layouts/header' %>
<div class='row'>

<h1>Select a square you want to create</h1>



<div class='bet hide large-10 large-offset-1 columns' >
<%= form_for(:bet, :url =>  bets_new_path,:remote=>true, :html => { :multipart => true} )  do |f| %>
 <div class="images_url row">
     

  </div> 

  </div>
   <div id="errorExplanation">  
  </div>
  <div class='field'>
   <%= f.select :charitytype, ["Lottery","Raffles","Bets","Appeals","Auctions", "Bid"] %>
  </div>


  
<div id="holder">
  </div> 
<!--   <p id="upload" class="hidden"><label>Drag & drop not supported, but you can still upload via this input field:<br><input type="file"></label></p>
  <p id="filereader">File API & FileReader API not supported</p>
  <p id="formdata">XHR2's FormData is not supported</p>
  <p id="progress">XHR2's upload progress isn't supported</p>
  <p>Upload progress: <progress id="uploadprogress" min="0" max="100" value="0">0</progress></p>
  <p>Drag an image from your desktop on to the drop zone above to see the browser both render the preview, but also upload automatically to this server.</p>
</article>
 -->
  <div class="upload-preview row"></div>
  
  <input id="file" name="bet[logo]" type="file">    
  
  <div class="hide">
  <%=f.number_field :user_id %>
  </div>

  <div class='field'>
   <%= f.label "Select a charity" %><br>
   <%= f.select :charityusersquare_id , @list %>
  </div>

  <div class="row">
    <%= f.label "Name" %><br>
    <%= f.text_field :name %>
  </div>

  <div class="row">
    <%= f.label "Description" %><br>
    <%= f.text_field :description %>
  </div>

  <div class="row">
    <%= f.label "Start date" %><br>
    <%= f.text_field :startdate, value: Time.now.to_s %>%>
  </div>

  <div class="row">
   <%= f.label "Ending date" %><br>
   <%= f.text_field :enddate ,{:class => 'datetimepicker'} %>
  </div>

  <div class="field" >
  <%= f.label "Bet Amount" %><br>
  <%= f.number_field :amount %>
  </div>

  <div class="row">
    <%= f.label 'Plese type your bet question' %><br>
    <%= f.text_area :question %>
  </div>

    <%= f.submit  %>
  </div>
<% end %> <br>

</div>

<div class='row'>
  <%= link_to 'Back', charity_path ,:class=>'button' %>
</div>

<script>
  $(document).ready(function(){
  $('.th').click(function(){
    var id= $(this).attr('id');
    $('.'+id).fadeIn(); 
  })
  $('.datetimepicker').datetimepicker();
  })
</script>

app/views/bets/bet_result.js.erb
$(".c"+<%=@betres.bet_id%>).html("<%=escape_javascript(render :partial=>"apply_result")%>");

app/views/bets/edit.html.erb
<div class="off-canvas-wrap docs-wrap" data-offcanvas="">
<div class="inner-wrap">
<%= render 'layouts/header' %>
<div class="inner_grey_bg">
<div class='row'>
<div class="create_squar_bet  create_squar left">
  <% if notice %>
    <p class="alert alert-success"><%= notice %></p>
  <% end %>
  <% if alert %>
    <div data-alert class="alert-box success radius">
      <%= alert %>
      <a href="#" class="close">&times;</a>
    </div>
  <% end %>

<div class='bet' >
  <div class="small-12 columns">
    <h1>Select a square you want to create</h1>
  </div>
<%= form_for(:bet, :url =>  update_bet_path, :html => { :multipart => true ,:id=>"new_bet"} )  do |f| %>
 <div class="images_url row">
     

  </div> 

   <div id="errorExplanation">

      <%= flash["error"] %>
   </div>
  <!-- <div class='field large-6 columns'> -->
  <!-- <label>Select Square type</label> -->
    <%#= f.select :charitytype, ["Lottery","Raffles","Bets","Appeals","Auctions", "Bid"],:selected => @crtrlr.capitalize %>
  <!-- </div> -->

  <div class="hide">


  <%=f.number_field :user_id , :value=>current_user.id %>
<%=f.number_field :id , :value=>@bet.id %>
<%=f.hidden_field :charitytype , :value => "bet" %>

  </div>

  <% if !@list.nil? %>
    <div class='field large-6 columns'>
      <%= f.label "Select a charity" %>
      <%= f.select :charityusersquare_id , @list , :selected => @bet.charityusersquare_id%>
    </div>
  <% end %>  

<!--   <div class="field large-6 columns">
    <%#= f.label "Name" %>
    <%#= f.text_field :name %>
  </div> -->
  <div class="field large-12 columns form-group">
    
    <%= f.label "Description" %>
    <%= f.text_area :description,:placeholder => "Enter bet description" %>
  </div>
   <div class="field large-6 columns">
   <%= f.label "Ending date" %>
   <%= f.text_field :enddate ,{:class => 'datetimepicker', :placeholder => 'Bet end date ',:required => true} %>
  </div>

  <div class='field large-6 columns'>
  <%= f.label "I bet" %> 
  <%= f.number_field :amount ,:placeholder=>'Enter amount in $', :min=> 1  %>
  </div>
  <div class='field large-6 columns'>
     <label>that</label> 
     <%= f.text_field :subject, :placeholder =>'Please enter the bet subject' ,:required => true %>
</div>
<div class='field large-6 columns'>
     <label>will</label>  
     <%= f.text_field :objective, :placeholder =>'Please enter the bet objective', :required => true %>
</div>


   
  <div class="create_squar_upload_image left">
    <div class="large-3 medium-4 small-12 columns">
       <div id="holder"></div> 
       <label> Add Photos </label>
        <div class="upload_image_squar text-center">
          <p>Click here or <br> drag &amp; drop</p>
          <input id="file" name="bet[logo]" type="file" >
        </div>
    </div>
    <div class="large-9 medium-8 small-12 columns">
      <label>Delete or rearrange your images</label>
      <div class="upload-preview">
         <%@charitypics.each do |c|%>
     <div class="image_preview_div pic<%=c.id%>">
     <img src='/images/<%=c.picture%>.jpg' style="height:100px;width:100px;">
     <span class="delete_image_bit1 imagefield2 " onClick=removediv('<%=c.id%>')></span>
   </div>
   
   <%end%>
        
      </div>
    </div>    
  </div>   


  

  <div class="invite large-12 left">         
    <%#= form_tag invite_path, method: :post do %>
      <div class="small-12 columns">
          <%= label_tag 'recipients', 'Invite users to bet' %>
        </div> 
        <div class="large-6 medium-6 small-12 columns"> 
        <p><%= select_tag 'recipients', recipients_options, multiple: true, class: 'form-control chosen-it', data: { placeholder: "Select Registered Users" } %></p>
        <div class='invite_btn left' >Invite more users</div>
      </div> 
      <div class="large-6 medium-6 small-12 columns"> 
        <div class='invite_sub' style='display:none'>
          <p><%= text_field_tag 'custom_recipients', nil, :placeholder => 'Add email and press enter', :class => "tm-input"  %></p>
          <p><%= hidden_field_tag 'url', request.original_url %></p>
          <p><%= hidden_field_tag 'bet_id', params[:id].to_i %></p>
        </div>
      </div> 
      <p><%#= submit_tag 'Send', class: 'tiny button' %></p>
    <%# end %> 
    <div class="msg large-12 columns">
    </div>                
  </div> 


  <div class="field bottom_ceate_bet_btn large-12 columns">



  <%= f.submit "Update Bet " , :class=>'button success' %>
  </div>

<% end %>


</div>
  </div>
</div>

  </div>
  </div>





<%= render 'layouts/footer' %>
<script src="http://ajax.aspnetcdn.com/ajax/jquery.validate/1.9/jquery.validate.min.js"></script>
<script src="https://code.jquery.com/ui/1.11.2/jquery-ui.js"></script>
<script>
$(document).ready(function(){
  // alert("on load");
   $(".upload-preview").sortable();
$('.th').click(function(){
 var id= $(this).attr('id');
 $('.'+id).fadeIn(); 
})

$('.datetimepicker').datetimepicker();


jQuery(".tm-input").tagsManager();
$('.chosen-it').chosen();



  $('.invite_btn').click(function(e){
    e.preventDefault();
    $('.invite_sub').toggle();

  });


/* validations for the form  */
$('.button.success').click(function(e){
  
   
        //e.preventDefault();

            //form validation rules
            $("#new_bet").validate({
                rules: {
                    'bet[description]': "required",
                    'bet[amount]': "required",
                    'bet[subject]': "required",
                    'bet[objective]':"required"

                   
                },
                messages: {
                    'bet[description]': "Please enter bet description *",
                    'bet[amount]': "Please enter bet amount ",
                    'bet[subject]': "Please enter bet subject ",
                    'bet[objective]':"Please enter bet objective"
                    
                },
                submitHandler: function(form) {
                    console.log('submit');
                    form.submit();
                }
            });


})

  });


function removediv(divid)
{   console.log('remove pic ..')
   $.ajax({
           type:'POST', 
           url: '/bet_removepic', 
           data: $.param({ pic: divid  })
      });
  $('.pic'+divid).remove();
}
/* end */



  
</script>
<script src="http://ajax.aspnetcdn.com/ajax/jquery.validate/1.9/jquery.validate.min.js"></script>
<style>
  button.success, .button.success {
    background-color: #43ac6a;
    border-color: #368a55;
    color: #ffffff;
    margin: 19px 19px 19px 0;
  }
  /* Error container for form C */

        #error-container div {
            color: red;
            line-height: 140%;
        }

        #error-container div:last-child {
            padding-bottom: 10px;
        }
        h1{
          font-family: "dinmedium";
        }
</style>

app/views/bets/follows.js.erb
<% if @follow_status == "follow"%>
    $('#follow').html('unfollow')
<%else%>
    $('#follow').html('follow')
<%end%>

app/views/bets/update.html.erb
var _html="";
_html+='<div data-alert class="alert-box success radius">';
<% @bet.errors.messages.each do |key,value| %>
_html+='<div>';
_html+= "<%= key.capitalize %> ";
_html+= "<%= value[0] %> ";
_html+='</div>';
<% end %>
_html+='<a href="#" class="close">&times;</a> ';
_html+='</div>'; 
$("#errorExplanation").html(_html);
$(document).foundation();