config/routes.rb
Rails.application.routes.draw do
 
  post '/rate' => 'rater#create', :as => 'rate'

  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  mount Ckeditor::Engine => '/ckeditor'
  devise_for :users ,:controllers => {:registrations => "user/registrations", :sessions => "user/sessions"}
  devise_scope :user do
  get "/sign_in" => "home#login"
  get "/sign_up"   => "home#user_signup"
  get "/charity_signup"   => "home#charity_signup"
  get "/account_settings"   => "home#account_settings"
  end

  resources :mysquares
  resources :squares

  
  root 'home#index'
  match '/searching'    => 'home#searching', :via => [:get,:post]
  match '/bets/create' =>'bets#create' , :via =>[:get,:post]
  match '/appeals/create' =>'appeals#create' , :via =>[:get,:post]
  match '/pay' => 'home#pay', :via => [:get,:post]
  get '/search' => 'home#search'
  match '/charity'    => 'charityusersquares#charity', :via => [:get,:post]
  match '/charity/upload'    => 'charity_media#upload', :via => [:get,:post]
  resources :charitychildren

  match '/profile'    => 'home#profile', :via => [:get,:post]
  match '/profile_edit/:id'    => 'home#profile_edit', :via => [:get,:post]
  match '/edit_profile'    => 'home#edit_profile', :via => [:get,:post,:patch]

  get '/charity/remove/:id', to: 'charity_media#remove_picture', as: 'remove_picture'

  match '/charityusersquares/buynow/:id' => 'charityusersquares#buynow' ,as: 'charitybuy_path' ,:via =>[:get,:post]

  resources :charityusersquares
 
  match '/charity_squares'    => 'home#charity_squares', :via => [:get,:post]
  match '/buy_now'    => 'home#buy_now', :via => [:get,:post]
  match '/bets/:id/edit'    => 'bets#edit', :via => [:get,:post]
  match '/bets/:id'    => 'bets#show', as: 'bets_show', :via => [:get,:post]
  match '/update_bet' =>'bets#update' , :via => [:get,:post]
  match '/bets/remove/:id' => 'bets#delete', :via => [:get,:post]
  match '/appeal/:id/edit'    => 'appeals#edit', :via => [:get,:post]
  match '/appeal/:id'    => 'appeals#show', as: 'appeals_show', :via => [:get,:post]
  match '/update_appeal' =>'appeals#update' , :via => [:get,:post]
  match '/auctions'    => 'home#auctions', :via => [:get,:post]
  match '/appeals'    => 'home#appeals', :via => [:get,:post]
  match '/raffle_n_lottery'    => 'home#raffle_n_lottery', :via => [:get,:post]

  match '/view_transaction'    => 'home#view_transaction', :via => [:get,:post]

  
  resources :conversations, only: [:index, :show, :destroy] do
    member do
      post :reply
      post :restore
      delete :empty_trash
      post :mark_as_read
    end
  end

  resources :messages, only: [:new, :create]
  match '/home_page_feed'    => 'home#home_page_feed', :via => [:get,:post]
  match '/search_filter'    => 'home#search_filter', :via => [:get,:post]
  match '/filter'    => 'home#filter', :via => [:get,:post]

  match '/completed_payment_request'    => 'home#completed_payment_request', :via => [:get,:post]
  match '/ipn_notification'    => 'home#ipn_notification', :via => [:get,:post]
  match '/appeal_ipn'  => 'appeals#appeal_ipn', :via => [:get,:post]

  match '/my_square'    => 'home#my_square', :via => [:get,:post]
  
  match '/profile'    => 'home#profile', :via => [:get,:post]
  match '/follow'    => 'charityusersquares#follow', :via => [:get,:post]
  match '/follows'    => 'bets#follows', :via => [:get,:post]
  match '/order_summary'    => 'home#order_summary', :via => [:get,:post]
  match '/bet_response'    => 'bets#bet_response', :via => [:get,:post]
  match '/bet_removepic'    => 'bets#removepic', :via => [:get,:post]
  match '/appeal_donations' => 'appeals#appeal_donations', :via => [:get,:post]
  match '/appeal_removepic'    => 'appeals#removepic', :via => [:get,:post] 
  match '/bet_result/:id'    => 'bets#bet_result', as: 'bet_result', :via => [:get,:post]
  match '/bet_result1/:id'    => 'bets#bet_result1', as: 'bet_result1', :via => [:get,:post]
  match '/view_donations/:id'  => 'appeals#view_donations', as: 'view_donations', :via => [:get,:post]
  match '/purchase/result/:id'    => 'home#purchase_result', as: 'purchase_result', :via => [:get,:post]
  match '/invite'    => 'bets#invite', :via => [:get,:post]

  match '/approve'  => 'bets#approve', :via =>[:get,:post]
  match '/purchase' => 'home#manage_purchase', :via =>[:get,:post]

  match '/checkout'    => 'home#checkout', :via => [:get,:post]
  match '/order_confirmation'    => 'home#order_confirmation', :via => [:get,:post]
  match '/view_transaction'    => 'home#view_transaction', :via => [:get,:post]
  match '/select'    => 'home#select', :via => [:get,:post]
  match '/create_square'    => 'charityusersquares#create_square', :via => [:get,:post]
  match '/bet'    => 'charityusersquares#bet', :via => [:get,:post]
  match '/appeal'  => 'charityusersquares#appeal', :via => [:get,:post]

end

app/models/appeal.rb
class Appeal < ActiveRecord::Base
end

app/controllers/appeals_controller.rb
class AppealsController < ApplicationController
  include ActionView::Helpers::DateHelper
  require 'paypal_adaptive'
  before_action :set_appeal, only: [:show, :edit,  :destroy]
  before_action :create, only: [:create]

  respond_to :html,:js

  def index
    @appeals = Appeal.all
    respond_with(@appeals)
  end
   
  def show
    if !current_user.nil?
      sign_out current_user
    end
    sign_in User.find(params[:user_id].to_i)
    @tz = Geocoder.search(current_user.current_sign_in_ip)[0].data["timezone"]
    respond_with(@appeal)
  end

  def new
    @appeal = Appeal.new
  end

  def edit
    @crtrlr = params[:controller]
    @charityusersquare = Charityusersquare.new
    @charityusersquareid=@charityusersquare.id
    @charitypics=CharityMedia.where(["charityusersquare_id = :u", { u: @appeal.id }])
    @charity=User.where("role = ?", 'charity')
    @list=[]
    @charity.each do |i|
    @list << [i.charityname,i.id]
    end
  end

  def create
    @appeal = Appeal.new(appeal_params)
    @appeal.user_id=params[:appeal][:user_id]
    @tz = Geocoder.search(current_user.current_sign_in_ip)[0].data["timezone"]
    @appeal.startdate = Time.now.in_time_zone(@tz).to_s
    if params[:appeal][:enddate].present?
      @appeal.enddate = params[:appeal][:enddate].in_time_zone(@tz).to_s
    end
    @appeal.charitytype=@appeal.charitytype.downcase
    @appeal.active = true
     if @appeal.save
      appeal_id=@appeal.id
      @params = params
      
     if params[:image_array]
     temp=[]
     params[:image_array].each do |encoded_img|
     appeal_media= CharityMedia.new(:charityusersquare_id=>appeal_id)
     appeal_media.save
     created_appeal_id=appeal_media.id
     path="#{Rails.root}/public/images/#{created_appeal_id}.jpg"
     temp.push path
         File.open("#{path}","wb") do |file|
         file.write(Base64.decode64(encoded_img.split(/,/)[1]))
         end
        
     @update=CharityMedia.find(created_appeal_id)
     @update.picture=@update.id
     @update.save()
      end
      end

      @appeal.startdate=@appeal.startdate.to_time.in_time_zone(@tz)
      @appeal.enddate=@appeal.enddate.to_time.in_time_zone(@tz)
      @time_left = distance_of_time_in_words(@appeal.enddate, @appeal.startdate)
      @time_in_minutes=(@appeal.enddate.to_time - @appeal.startdate.to_time)/60
      
      @time_enque=@time_in_minutes.floor
  
      Delayed::Job.enqueue(MailingJob.new(@appeal.user_id, @appeal.id), -3, @time_enque.minutes.from_now.in_time_zone(@tz))
      flash[:notice]= "Appeal Created" 
      redirect_to my_square_path
      else
         
       flash[:alert] = @appeal.errors.full_messages.to_sentence
      redirect_to(new_charityusersquare_path) 
     end
  end

  def update
     @tz = Geocoder.search(current_user.current_sign_in_ip)[0].data["timezone"]
     @appealid=params[:appeal][:id]

     @appeal=Appeal.find(@appealid)
     @startdate = Time.now.in_time_zone(@tz).to_s
    if params[:appeal][:enddate].present?
      @enddate = params[:appeal][:enddate].in_time_zone(@tz).to_s
    end

    @appeal.update_attributes!(:user_id => params[:appeal][:user_id] , :charityusersquare_id =>params[:appeal][:charityusersquare_id], :description => params[:appeal][:description], :appeal_type => params[:appeal][:appeal_type], :enddate =>@enddate, :charitytype=>params[:appeal][:charitytype].downcase, :specific_appeal_description=>params[:appeal][:specific_appeal_description])
   
      appeal_id=@appealid
      @params = params
          
          if params[:image_array]
           temp=[]
           params[:image_array].each do |encoded_img|
            

           appeal_media= CharityMedia.new(:charityusersquare_id=>appeal_id)
           appeal_media.save
           created_appeal_id=appeal_media.id
           path="#{Rails.root}/public/images/#{created_appeal_id}.jpg"
           temp.push path
               File.open("#{path}","wb") do |file|
               file.write(Base64.decode64(encoded_img.split(/,/)[1]))
               end
              
           @update=CharityMedia.find(created_bet_id)
           @update.picture=@update.id
           @update.save()

          end
        end

      @startdate=@startdate.to_time.in_time_zone(@tz)
      @enddate=@enddate.to_time.in_time_zone(@tz)
      @time_left = distance_of_time_in_words(@enddate, @startdate)
      @time_in_minutes=(@enddate.to_time - @startdate.to_time)/60
      
      @time_enque=@time_in_minutes.floor
  
      Delayed::Job.enqueue(MailingJob.new(@appeal.user_id, @appeal.id), -3, @time_enque.minutes.from_now.in_time_zone(@tz))
      flash[:notice]= "Appeal Updated" 
      redirect_to my_square_path
  end

  def destroy
    @appeal.destroy
    respond_with(@appeal)
  end

  def appeal_donations
    @appeal_donations = AppealDonation.new
    @appeal_donations.user_id = params[:user_id]
    @appeal_donations.appeal_id = params[:appeal_id]
    @appeal_donations.amount = params[:amount]
    @appeal_donations.save
    flash[:notice]= "Thank You for Donation!!!" 

    pay_request = PaypalAdaptive::Request.new
    data = {"returnUrl" => "http://esferasoftsolutions.com/order_confirmation?appeal_id=#{params[:appeal_id].to_i}&user_id=#{params[:user_id].to_i}&price=#{params[:amount]}", "requestEnvelope" => {"errorLanguage" => "en_US"}, "currencyCode"=>"USD", "receiverList"=>{"receiver"=>[{ "email"=>User.find_by_id(params[:user_id].to_i).paypal_email, "amount"=>params[:amount].to_f - ((5 * params[:amount].to_f)/100), "appealid"=>params[:appeal_id], "userid"=> params[:user_id]}, {"email"=>"charity-admin@esferasoft.com", "amount"=>(5 * params[:amount].to_f)/100}]}, "cancelUrl"=>"http://esferasoftsolutions.com/canceled_payment_request", "actionType"=>"PAY", "ipnNotificationUrl"=>"http://esferasoftsolutions.com/appeal_ipn?user_id=#{params[:user_id]}&appeal_id=#{params[:appeal_id]}&charitytype=#{params[:charitytype]}"}
    pay_response = pay_request.pay(data)
      
    if pay_response.success?
      redirect_to pay_response.approve_paypal_payment_url
    end 
    
  end

  def view_donations
    @appeal_donations = AppealDonation.where("appeal_id=?", params[:id])
  end  

  def removepic
   @mediaid=params[:pic]
   CharityMedia.find(@mediaid).destroy
   render :js => 'deleted'
  end 

  def approve
   @appeal=Appeal.where(:id=>params[:id])
   @appeal.first.active= true
   @appeal.first.save
   flash[:notice]= "Appeal Aprroved" 
   redirect_to my_square_path
  end 

  def appeal_ipn
    @params = params
    ipn = PaypalAdaptive::IpnNotification.new
    ipn.send_back(env['rack.request.form_vars'])
    if ipn.verified?
      @payment= PaymentDetail.new 
      @payment.transaction_id = params["transaction"]["0"][".id_for_sender_txn"]
      @payment.sender_email = params["sender_email"]
      @payment.receiver_email = params["transaction"]["0"][".receiver"]
      @payment.date = params["payment_request_date"]
      @payment.charitytype = params["charitytype"]
      @payment.amount = params["transaction"]["0"][".amount"].scan(/\d+/).first.to_f
      @payment.user_id = params["user_id"].to_i
      @payment.appeal_id = params["appeal_id"].to_i
      @payment.save
    else
      logger.info "IT DIDNT WORK"
    end

    render nothing: true
   end


  private
    def set_appeal
      @appeal = Appeal.find(params[:id])    
    end

    def appeal_params
      params.require(:appeal).permit(:user_id, :charitytype, :charityusersquare_id, :description, :enddate, :image_array, :startdate, :active, :appeal_type, :specific_appeal_description)
    end
end

app/views/appeals/edit.html.erb
<div class="off-canvas-wrap docs-wrap" data-offcanvas="">
<div class="inner-wrap">
<%= render 'layouts/header' %>
<div class="inner_grey_bg">
<div class='row'>
<div class="create_squar_bet  create_squar left">
  <% if notice %>
    <p class="alert alert-success"><%= notice %></p>
  <% end %>
  <% if alert %>
    <div data-alert class="alert-box success radius">
      <%= alert %>
      <a href="#" class="close">&times;</a>
    </div>
  <% end %>

<div class='appeal' >
  <div class="small-12 columns">
    <h1>Select a square you want to create</h1>
  </div>
<%= form_for(:appeal, :url =>  update_appeal_path, :html => { :multipart => true ,:id=>"new_appeal"} )  do |f| %>
 <div class="images_url row">
     

  </div> 

   <div id="errorExplanation">

      <%= flash["error"] %>
   </div>
  <!-- <div class='field large-6 columns'> -->
  <!-- <label>Select Square type</label> -->
    <%#= f.select :charitytype, ["Lottery","Raffles","Bets","Appeals","Auctions", "Bid"],:selected => @crtrlr.capitalize %>
  <!-- </div> -->

  <div class="hide">


  <%=f.number_field :user_id , :value=>current_user.id %>
  <%=f.number_field :id , :value=>@appeal.id %>
  <%=f.hidden_field :charitytype , :value => "appeal" %>

  </div>

  <% if !@list.nil? %>
    <div class='field large-6 columns'>
      <%= f.label "Select a charity" %>
      <%= f.select :charityusersquare_id , @list , :selected => @appeal.charityusersquare_id%>
    </div>
  <% end %>  

<!--   <div class="field large-6 columns">
    <%#= f.label "Name" %>
    <%#= f.text_field :name %>
  </div> -->


  <div class="field large-12 columns form-group"> 
    <%= f.label "Description" %>
    <%= f.text_area :description,:placeholder => "Enter description" %>
  </div>
  <div class='field large-6 columns'>
    <%= f.label "Type" %> 
    <%= f.select :appeal_type, ["General", "Specific"],:selected =>@appeal.appeal_type %>
  </div>

  <div class="field large-6 columns">
    <%= f.label "Ending date" %>
    <%= f.text_field :enddate ,{:class => 'datetimepicker', :placeholder => 'Appeal end date ',:required => true} %>
  </div>

    <div class='field large-6 columns specific'>
      <%= f.label :specific_appeal_description, "Appeal Description" %>
      <%= f.text_field :specific_appeal_description %>
    </div>

  <div class="create_squar_upload_image left">
    <div class="large-3 medium-4 small-12 columns">
       <div id="holder"></div> 
       <label> Add Photos </label>
        <div class="upload_image_squar text-center">
          <p>Click here or <br> drag &amp; drop</p>
          <input id="file" name="appeal[logo]" type="file" >
        </div>
    </div>
    <div class="large-9 medium-8 small-12 columns">
      <label>Delete or rearrange your images</label>
      <div class="upload-preview">
         <%@charitypics.each do |c|%>
     <div class="image_preview_div pic<%=c.id%>">
     <img src='/images/<%=c.picture%>.jpg' style="height:100px;width:100px;">
     <span class="delete_image_bit1 imagefield2 " onClick=removediv('<%=c.id%>')></span>
   </div>
   
   <%end%>
        
      </div>
    </div>    
  </div>   


  <div class="field bottom_ceate_bet_btn large-12 columns">

  <%= f.submit "Update Appeal " , :class=>'button success' %>
  </div>

<% end %>


</div>
  </div>
</div>

  </div>
  </div>





<%= render 'layouts/footer' %>

<script>
$(document).ready(function(){
  // alert("on load");
$('.th').click(function(){
 var id= $(this).attr('id');
 $('.'+id).fadeIn(); 
})

$('.datetimepicker').datetimepicker();

/* validations for the form  */
$('.button.success').click(function(e){
  
   
        //e.preventDefault();

            //form validation rules
            $("#new_appeal").validate({
                rules: {
                    'appeal[description]': "required"
                },
                messages: {
                    'appeal[description]': "Please enter description *"
                },
                submitHandler: function(form) {
                    console.log('submit');
                    form.submit();
                }
            });


})

$('#appeal_appeal_type').change(function() {
      location.reload();
  });  
  if ($("#appeal_appeal_type :selected").text() == "Specific")
  {
    $(".specific").show();
  }
  else {
    $(".specific").hide();
  }
 
  });

function removediv(divid)
{   console.log('remove pic ..')
   $.ajax({
           type:'POST', 
           url: '/appeal_removepic', 
           data: $.param({ pic: divid  })
      });
  $('.pic'+divid).remove();
}
/* end */



  
</script>
<script src="http://ajax.aspnetcdn.com/ajax/jquery.validate/1.9/jquery.validate.min.js"></script>
<style>
  button.success, .button.success {
    background-color: #43ac6a;
    border-color: #368a55;
    color: #ffffff;
    margin: 19px 19px 19px 0;
  }
  /* Error container for form C */

        #error-container div {
            color: red;
            line-height: 140%;
        }

        #error-container div:last-child {
            padding-bottom: 10px;
        }
        h1{
          font-family: "dinmedium";
        }
</style>

app/views/appeals/show.html.erb
  <div class="off-canvas-wrap docs-wrap" data-offcanvas="">
      <div class="inner-wrap">
<%= render 'layouts/navigation' %>

        <section class="inner_grey_bg">
          <div class="charity_feed left">
            <div class="row ">
              <div class="large-12 medium-12 small-12 columns">
                <ul class="Square_breadcrumb left">
                  <li>
                    <!-- <a href="#" title="breadcrumb ">breadcrumb</a> -->
                  </li>
                  <li>
                    <!-- <a href="#" title="breadcrumb ">breadcrumb</a> -->
                  </li>
                  <li>
                    <!-- <a href="#" title="breadcrumb ">breadcrumb</a> -->
                  </li>
                </ul>
              </div>  
              <div class="large-6 medium-6 small-12 columns">

                <div class="square_page_slider left">
                  <div class="square_page_slider_big_img left"> 
                   <% if !CharityMedia.where(:charityusersquare_id=>@appeal.id).blank? %> 
                    <img src="/images/<%=CharityMedia.where(:charityusersquare_id=>@appeal.id).first.picture%>.jpg">
                   <%end%> 
                  </div>
                  <ul class="square_page_slider_thumb right">
                   <% @charitymedia = CharityMedia.where(:charityusersquare_id=>@appeal.id)%>
                     <% @charitymedia.each do |i|%>
                     <li> <a class='/images/<%=i.picture%>.jpg' href="javascript:void(0);">
                     <img src="/images/<%=i.picture%>.jpg">
                       <li></a>
                     <% end %>
                  </ul>
                </div>

              </div>

              <div class="large-6 medium-6 small-12 columns">
                <div class="square_page_about_pro_right left">
                  <h1><%= @appeal.appeal_type%></h1>
                    <div class="about_square_page_user left">
                     <span class="about_square_page_user_img_thumb left" style="background-image:url('/images/profile/<%= User.find_by_id(@appeal.user_id).profile_image %>');background-size:cover;">
                     </span>
                    <span class="about_square_page_user_img_name left">
                       by <%= User.find_by_id(@appeal.user_id).firstname %> 
                      <span class="about_square_page_user_feedback left">Feedback 100%</span>
                    </span>
                  </div>
                  <div class="about_square_page_time_price time_down left">
                    <span class="about_square_time left">
                      Time left:
                      <% start_time = Time.now.in_time_zone(@tz) %>

                      <% end_time   =  Appeal.find(params[:id]).enddate.in_time_zone(@tz) %>
                      <% if start_time > end_time %>
                        <% diff = 0 %>
                      <% else %> 
                        <% diff = 1 %> 
                        <% @time_in_minutes=(Appeal.find(params[:id]).enddate.in_time_zone(@tz) - Time.now.in_time_zone(@tz))/60 %>
                        <% @time_enque=@time_in_minutes.floor %>
                      <% end %>  
                      <span class="time_price left" id="until2d">
                      <%#= distance_of_time_in_words(start_time, end_time)  %></span>
                      <!-- <span id="text"></span> -->
                    </span>
                   
                  </div>
                  
                  <!-- 


                      Price 
                      <span class="time_price left">£<%#= @bet.amount%></span>
                    </span>
                  </div>


                  <div class="select_size_quantity right">
                    <select class="right">
                      <option>quantity</option>
                      <option>1</option>
                      <option>2</option>
                      <option>3</option>
                    </select>

                    <select class="right">
                      <option>size</option>
                      <option>1</option>
                      <option>2</option>
                      <option>3</option>
                    </select>


                  </div> -->

                  <div class="inv large-6 medium-6 small-12 columns">
                    <%= form_tag appeal_donations_path, method: :post, :class =>"frm1" do %>
                      <%= label_tag "amount", "Donation amount" %><br/>
                      <%= text_field_tag "amount" %>
                      <%= hidden_field_tag "appeal_id", params[:id] %>
                      <%= hidden_field_tag "user_id", current_user.id %>
                      <%= hidden_field_tag "charitytype", "Appeals" %>
                      <%= submit_tag "Donate", :class => "button left" %>
                    <% end %>
                  </div> 

                  <a class="left text-center " href="#" title="add to watch list">add to watch list</a>
                  </div>

                  <ul class="sequre_address_list left">
                   <!--  <li><span class="grey_color">Delivery:</span> Free delivery (UK only) or Pick-up from seller</li>
                    <li><span class="grey_color">Location:</span> London, UK</li>
                    <li><span class="grey_color">Payment:</span> Paypal, Debit and Credit cards</li> -->
                  </ul>
                </div>
              </div>
            </div>
            <div class="about_squre_charity left">
              <div class="row">
                <div class="large-12 medium-12 small-12 columns">
                  <div class="squre_charity_follow_share_outer my_profile_share right">
                            <div class="squre_charity_follow_share right">
                              <!-- <a title="follow" href="#">follow</a> --><!-- User.find_by_id(@bet.charityusersquare_id) -->
                              <%#= link_to User.find(@bet.charityusersquare_id).follow_status, follows_path(:id =>@bet.charityusersquare_id), :id => "follow", :remote => true %>
                              <!-- <a title="follow" href="#">follow</a> -->
                              <a title="share" href="javascript:void(0)" id="share">share</a>
                                <div class="tooltip_share" style="display: none;">
                                  <ul class="social_share">

                                    <li> <%= render_shareable :buttons=> ['twitter'] %> </li>
                                    <li> <%= render_shareable :buttons=> ['facebook'] %> </li>
                                    <!-- <li> <a class="you_tube_share" href="#"> </a> </li>
                                    <li> <a class="facebook_share" href="#"> </a> </li> -->
                                  </ul>

                                </div>
                            </div>
                          </div>

                  <%@charity=User.where(:id=>@appeal.charityusersquare_id)%>

                  <div class="squre_charity_img left" style="background-image:url('/images/profile/<%=@charity.first.profile_image%>'); background-size: cover; background-position: center center;">

                    
                  </div>
                
                 <div class="squre_charity_content left">
                    <%@charity=User.where(:id=>@appeal.charityusersquare_id)%>
                    <h1><%=@charity.first.charityname%></h1>
                    <span class="about_squre_charity_name left">
                     <%= @charity.first.firstname%>
                    </span>
                    <p><%= @charity.first.mission%></p>

                  </div>
                </div>  
              </div>
            </div>

         
            
            <div class="row">
              <div class="large-12 columns">
                <h3>suggestions</h3>
              </div>
              <%@appealall=Appeal.where(:active => 1 ) %>
              <%@appealall.each do |c|%>
             <a href=<%="/appeal/#{c.id}"%>>
             <div class="large-4 medium-6 small-12 columns">
                    <div class="charity_feed_box left">
                      <div class="charity_box_img left">

                       <% @cmedia = CharityMedia.where(:charityusersquare_id => c.id)%>
                        <% if !@cmedia.blank? %>                    
                          <img src="/images/<%=@cmedia.first.picture%>.jpg">
                       <% end %>

                      </div>
                      <div class="charity_feed_box_contant left">
                        <h1><%= c.description%></h1>
                        <span class="charity_feed_box_contant_user">
                          by <%= User.find_by_id(c.user_id).firstname %>
                        </span>
                        <div class="charity_feed_box_user_detail left">
                         <span class="about_square_page_user_img_thumb left" style="background-image:url('/images/profile/<%= User.find_by_id(c.user_id).profile_image %>');background-size:cover;"></span>
                          <span class="charity_feed_box_time left">
                            <% start_time = Time.now.in_time_zone(@tz).to_s %>
                            <% end_time   =  Appeal.find(params[:id]).enddate.in_time_zone(@tz).to_s %>
                            <% if start_time > end_time %>
                                Time left <br><span class="charity_feed_box_day"><%#= s.enddate %>Time Over</span>
                            <% else %> 
                              Time left <br><span class="charity_feed_box_day"><%#= s.enddate %><%= distance_of_time_in_words(end_time, start_time)  %></span>
                            <% end %>
                       
                          </span>

                          <% if c.charitytype == "Auctions" %>
                            <span class="charity_feed_box_buy right">
                              <a href="#" title="Buy now">Buy now</a>
                            </span>
                          <% elsif c.charitytype == "Appeals" %>  
                            <span class="charity_feed_box_donate right">
                              <a href="#" title="Donate">Donate</a>
                            </span>
                          <% elsif c.charitytype == "Bid" %>
                            <span class="charity_feed_box_Bid right">
                              <a href="#" title="Bid now">Bid now</a>
                            </span>
                          <% elsif c.charitytype == "Bets" %> 
                            <span class="charity_feed_box_place_bet right">
                              <a href="#" title="Place bet">Place bet</a>
                            </span> 
                          <% elsif c.charitytype == "Lottery" %>  
                            <span class="charity_feed_box_play_lottery right">
                              <a href="#" title="Play lottery">Play lottery</a>
                            </span>
                          <% elsif c.charitytype == "Raffles" %>  
                            <span class="charity_feed_box_play_raffle right">
                              <a href="#" title="Play raffle">Play raffle</a>
                            </span>
                          <% else %>
                          <% end %>  
                        </div>
                      </div>
                    </div>

                  </div> 
                  </a>
               <%end%>

            
            </div>    
          </div> 

<%= render 'layouts/footer' %>


</div>
</div>


<script type="text/javascript">
  $("document").ready(function(){

    $('.chosen-it').chosen();
    $("#share").click(function(){
      $(".tooltip_share").toggle();
    });

    $("#share").click(function(){
      $(".tooltip_share").toggle();
    });

  });
</script>

<script type="text/javascript">

  $(function () { 
   var diff ="<%=diff%>";

      if (diff == 0) {
        $('#until2d').countdown({until: '+0'});
      }

      else {
        $('#until2d').countdown({until: '+<%= @time_enque %>m'});
      } 
      $(".square_page_slider_thumb li a").click(function(){
      var img=$(this).attr('class');
      $('.square_page_slider_big_img img').attr('src',img);
      })
    
    });
  
</script>

<style>

#until2d{
  width: 301px;
  height: 59px;
  padding-top: 6px;
}
</style>